
services:
  - type: web
    name: vertex-trading
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PESAPAL_CONSUMER_KEY
        sync: false
      - key: PESAPAL_CONSUMER_SECRET
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
