
services:
  - type: web
    name: vertex-trading
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PESAPAL_CONSUMER_KEY
        sync: false
      - key: PESAPAL_CONSUMER_SECRET
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: PORT
        value: 10000
